// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIrM1VD-nwT4lAEmr8icQGLfTDaF9ODMA',
    appId: '1:1030288314545:web:d46009ecbb274a64cc9290',
    messagingSenderId: '1030288314545',
    projectId: 'barkbook-2022',
    authDomain: 'barkbook-2022.firebaseapp.com',
    storageBucket: 'barkbook-2022.appspot.com',
    measurementId: 'G-0ZWE5DF8FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb7LpykZ18HWX8BvZA3E4why7Egt0Dc8k',
    appId: '1:1030288314545:android:f47968956eec7db5cc9290',
    messagingSenderId: '1030288314545',
    projectId: 'barkbook-2022',
    storageBucket: 'barkbook-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2n-tpWAnDyDK5jMSrhFtEVln2BHVOcI',
    appId: '1:1030288314545:ios:5f23364f34287427cc9290',
    messagingSenderId: '1030288314545',
    projectId: 'barkbook-2022',
    storageBucket: 'barkbook-2022.appspot.com',
    androidClientId: '1030288314545-fgmdnnnde18d0djsrpus6bbjh08duo5u.apps.googleusercontent.com',
    iosClientId: '1030288314545-6p5tv3d4gb2j94pis4lg27hva3sgfl4l.apps.googleusercontent.com',
    iosBundleId: 'com.capstone.app',
  );
}
